// División política de Chile — comunas y ciudades por región.
//
// Generado el 2026-09-25 desde datasets públicos de la DPA
// (SUBDERE) y el listado de ciudades del INE:
//   comunas:  https://gist.github.com/juanbrujo/0fd2f4d126b3ce5a95a7dd1f28b3d8dd
//   ciudades: https://github.com/vicentezaror/regiones-chile
// 16 regiones · 346 comunas · 232 ciudades.
//
// Las claves son los mismos ids de región de `lib/regions.ts`, que es lo que se
// guarda en `installations.region_id` y lo que usa el simulador.
//
// No editar a mano: si hay que actualizarlo, regenerar desde las fuentes.

import { REGIONS } from './regions';

export interface RegionGeo {
  comunas: string[];
  ciudades: string[];
}

/** Valor que ofrece el combo para lo que no está en la lista. */
export const OTRA = 'Otra';

export const CHILE_GEO: Record<string, RegionGeo> = {
  'arica-parinacota': {
    comunas: [
      'Arica',
      'Camarones',
      'General Lagos',
      'Putre',
    ],
    ciudades: [
      'Arica',
      'Putre',
    ],
  },
  'tarapaca': {
    comunas: [
      'Alto Hospicio',
      'Camiña',
      'Colchane',
      'Huara',
      'Iquique',
      'Pica',
      'Pozo Almonte',
    ],
    ciudades: [
      'Alto Hospicio',
      'Iquique',
      'Pozo Almonte',
    ],
  },
  'antofagasta': {
    comunas: [
      'Antofagasta',
      'Calama',
      'María Elena',
      'Mejillones',
      'Ollagüe',
      'San Pedro de Atacama',
      'Sierra Gorda',
      'Taltal',
      'Tocopilla',
    ],
    ciudades: [
      'Antofagasta',
      'Calama',
      'Mejillones',
      'San Pedro de Atacama',
      'Taltal',
      'Tocopilla',
    ],
  },
  'atacama': {
    comunas: [
      'Alto del Carmen',
      'Caldera',
      'Chañaral',
      'Copiapó',
      'Diego de Almagro',
      'Freirina',
      'Huasco',
      'Tierra Amarilla',
      'Vallenar',
    ],
    ciudades: [
      'Caldera',
      'Chañaral',
      'Copiapó',
      'Diego de Almagro',
      'El Salvador',
      'Huasco',
      'Tierra Amarilla',
      'Vallenar',
    ],
  },
  'coquimbo': {
    comunas: [
      'Andacollo',
      'Canela',
      'Combarbalá',
      'Coquimbo',
      'Illapel',
      'La Higuera',
      'La Serena',
      'Los Vilos',
      'Monte Patria',
      'Ovalle',
      'Paiguano',
      'Punitaqui',
      'Río Hurtado',
      'Salamanca',
      'Vicuña',
    ],
    ciudades: [
      'Andacollo',
      'Canela',
      'Combarbalá',
      'Coquimbo',
      'El Palqui',
      'Illapel',
      'La Serena',
      'Los Vilos',
      'Monte Patria',
      'Ovalle',
      'Punitaqui',
      'Salamanca',
      'Tongoy',
      'Vicuña',
    ],
  },
  'valparaiso': {
    comunas: [
      'Algarrobo',
      'Cabildo',
      'Calera',
      'Calle Larga',
      'Cartagena',
      'Casablanca',
      'Catemu',
      'Concón',
      'El Quisco',
      'El Tabo',
      'Hijuelas',
      'Isla de Pascua',
      'Juan Fernández',
      'La Cruz',
      'La Ligua',
      'Limache',
      'Llaillay',
      'Los Andes',
      'Nogales',
      'Olmué',
      'Panquehue',
      'Papudo',
      'Petorca',
      'Puchuncaví',
      'Putaendo',
      'Quillota',
      'Quilpué',
      'Quintero',
      'Rinconada',
      'San Antonio',
      'San Esteban',
      'San Felipe',
      'Santa María',
      'Santo Domingo',
      'Valparaíso',
      'Villa Alemana',
      'Viña del Mar',
      'Zapallar',
    ],
    ciudades: [
      'Algarrobo',
      'Cabildo',
      'Calle Larga',
      'Cartagena',
      'Casablanca',
      'Catemu',
      'Concón',
      'El Melón',
      'El Quisco',
      'El Tabo',
      'Hanga Roa',
      'Hijuelas',
      'Juan Fernández',
      'La Calera',
      'La Cruz',
      'La Ligua',
      'Las Cruces',
      'Las Ventanas',
      'Limache',
      'Llay-Llay',
      'Los Andes',
      'Nogales',
      'Olmué',
      'Puchuncaví',
      'Putaendo',
      'Quillota',
      'Quilpué',
      'Quintero',
      'Rinconada',
      'San Antonio',
      'San Esteban',
      'San Felipe',
      'Santa María',
      'Santo Domingo',
      'Valparaíso',
      'Villa Alemana',
      'Villa Los Almendros',
      'Viña del Mar',
    ],
  },
  'ohiggins': {
    comunas: [
      'Chépica',
      'Chimbarongo',
      'Codegua',
      'Coinco',
      'Coltauco',
      'Doñihue',
      'Graneros',
      'La Estrella',
      'Las Cabras',
      'Litueche',
      'Lolol',
      'Machalí',
      'Malloa',
      'Marchihue',
      'Mostazal',
      'Nancagua',
      'Navidad',
      'Olivar',
      'Palmilla',
      'Paredones',
      'Peralillo',
      'Peumo',
      'Pichidegua',
      'Pichilemu',
      'Placilla',
      'Pumanque',
      'Quinta de Tilcoco',
      'Rancagua',
      'Rengo',
      'Requínoa',
      'San Fernando',
      'San Vicente',
      'Santa Cruz',
    ],
    ciudades: [
      'Chépica',
      'Chimbarongo',
      'Codegua',
      'Coltauco',
      'Doñihue',
      'Graneros',
      'Gultro',
      'La Punta',
      'Las Cabras',
      'Lo Miranda',
      'Los Lirios',
      'Machalí',
      'Nancagua',
      'Peralillo',
      'Peumo',
      'Pichidegua',
      'Pichilemu',
      'Punta Diamante',
      'Quinta de Tilcoco',
      'Rancagua',
      'Rengo',
      'Requínoa',
      'San Fernando',
      'San Francisco de Mostazal',
      'San Vicente de Tagua Tagua',
      'Santa Cruz',
    ],
  },
  'maule': {
    comunas: [
      'Cauquenes',
      'Chanco',
      'Colbún',
      'Constitución',
      'Curepto',
      'Curicó',
      'Empedrado',
      'Hualañé',
      'Licantén',
      'Linares',
      'Longaví',
      'Maule',
      'Molina',
      'Parral',
      'Pelarco',
      'Pelluhue',
      'Pencahue',
      'Rauco',
      'Retiro',
      'Río Claro',
      'Romeral',
      'Sagrada Familia',
      'San Clemente',
      'San Javier',
      'San Rafael',
      'Talca',
      'Teno',
      'Vichuquén',
      'Villa Alegre',
      'Yerbas Buenas',
    ],
    ciudades: [
      'Cauquenes',
      'Colbún',
      'Constitución',
      'Culenar',
      'Curicó',
      'Hualañé',
      'Linares',
      'Lo Figueroa de Pencahue',
      'Longaví',
      'Maule',
      'Molina',
      'Parral',
      'Rauco',
      'Retiro',
      'Romeral',
      'San Clemente',
      'San Javier',
      'Talca',
      'Teno',
      'Villa Alegre',
    ],
  },
  'nuble': {
    comunas: [
      'Bulnes',
      'Chillán',
      'Chillán Viejo',
      'Cobquecura',
      'Coelemu',
      'Coihueco',
      'El Carmen',
      'Ninhue',
      'Ñiquén',
      'Pemuco',
      'Pinto',
      'Portezuelo',
      'Quillón',
      'Quirihue',
      'Ránquil',
      'San Carlos',
      'San Fabián',
      'San Ignacio',
      'San Nicolás',
      'Treguaco',
      'Yungay',
    ],
    ciudades: [
      'Bulnes',
      'Chillán',
      'Chillán Viejo',
      'Coelemu',
      'Coihueco',
      'Quillón',
      'Quirihue',
      'San Carlos',
      'Yungay',
    ],
  },
  'biobio': {
    comunas: [
      'Alto Biobío',
      'Antuco',
      'Arauco',
      'Cabrero',
      'Cañete',
      'Chiguayante',
      'Concepción',
      'Contulmo',
      'Coronel',
      'Curanilahue',
      'Florida',
      'Hualpén',
      'Hualqui',
      'Laja',
      'Lebu',
      'Los Álamos',
      'Los Ángeles',
      'Lota',
      'Mulchén',
      'Nacimiento',
      'Negrete',
      'Penco',
      'Quilaco',
      'Quilleco',
      'San Pedro de la Paz',
      'San Rosendo',
      'Santa Bárbara',
      'Santa Juana',
      'Talcahuano',
      'Tirúa',
      'Tomé',
      'Tucapel',
      'Yumbel',
    ],
    ciudades: [
      'Arauco',
      'Cabrero',
      'Cañete',
      'Chiguayante',
      'Concepción',
      'Contulmo',
      'Coronel',
      'Curanilahue',
      'Florida',
      'Hualpén',
      'Hualqui',
      'Huépil',
      'La Laja',
      'Laraquete',
      'Lebu',
      'Los Álamos',
      'Los Ángeles',
      'Lota',
      'Monte Águila',
      'Mulchén',
      'Nacimiento',
      'Penco',
      'San Pedro de la Paz',
      'San Rosendo',
      'Santa Bárbara',
      'Santa Juana',
      'Talcahuano',
      'Tomé',
      'Yumbel',
    ],
  },
  'araucania': {
    comunas: [
      'Angol',
      'Carahue',
      'Cholchol',
      'Collipulli',
      'Cunco',
      'Curacautín',
      'Curarrehue',
      'Ercilla',
      'Freire',
      'Galvarino',
      'Gorbea',
      'Lautaro',
      'Loncoche',
      'Lonquimay',
      'Los Sauces',
      'Lumaco',
      'Melipeuco',
      'Nueva Imperial',
      'Padre Las Casas',
      'Perquenco',
      'Pitrufquén',
      'Pucón',
      'Purén',
      'Renaico',
      'Saavedra',
      'Temuco',
      'Teodoro Schmidt',
      'Toltén',
      'Traiguén',
      'Victoria',
      'Vilcún',
      'Villarrica',
    ],
    ciudades: [
      'Angol',
      'Cajón',
      'Carahue',
      'Collipulli',
      'Cunco',
      'Curacautín',
      'Freire',
      'Gorbea',
      'Labranza',
      'Lautaro',
      'Loncoche',
      'Nueva Imperial',
      'Padre Las Casas',
      'Pitrufquén',
      'Pucón',
      'Purén',
      'Renaico',
      'Temuco',
      'Traiguén',
      'Victoria',
      'Vilcún',
      'Villarrica',
    ],
  },
  'los-rios': {
    comunas: [
      'Corral',
      'Futrono',
      'La Unión',
      'Lago Ranco',
      'Lanco',
      'Los Lagos',
      'Máfil',
      'Mariquina',
      'Paillaco',
      'Panguipulli',
      'Río Bueno',
      'Valdivia',
    ],
    ciudades: [
      'Corral',
      'Futrono',
      'La Unión',
      'Lanco',
      'Los Lagos',
      'Paillaco',
      'Panguipulli',
      'Río Bueno',
      'San José de la Mariquina',
      'Valdivia',
    ],
  },
  'los-lagos': {
    comunas: [
      'Ancud',
      'Calbuco',
      'Castro',
      'Chaitén',
      'Chonchi',
      'Cochamó',
      'Curaco de Vélez',
      'Dalcahue',
      'Fresia',
      'Frutillar',
      'Futaleufú',
      'Hualaihué',
      'Llanquihue',
      'Los Muermos',
      'Maullín',
      'Osorno',
      'Palena',
      'Puerto Montt',
      'Puerto Octay',
      'Puerto Varas',
      'Puqueldón',
      'Purranque',
      'Puyehue',
      'Queilén',
      'Quellón',
      'Quemchi',
      'Quinchao',
      'Río Negro',
      'San Juan de la Costa',
      'San Pablo',
    ],
    ciudades: [
      'Alerce',
      'Ancud',
      'Calbuco',
      'Castro',
      'Chaitén',
      'Chonchi',
      'Dalcahue',
      'Fresia',
      'Frutillar',
      'Llanquihue',
      'Los Muermos',
      'Osorno',
      'Puerto Montt',
      'Puerto Varas',
      'Purranque',
      'Quellón',
      'Río Negro',
    ],
  },
  'aysen': {
    comunas: [
      'Aysén',
      'Chile Chico',
      'Cisnes',
      'Cochrane',
      'Coyhaique',
      'Guaitecas',
      'Lago Verde',
      'O\'Higgins',
      'Río Ibáñez',
      'Tortel',
    ],
    ciudades: [
      'Chile Chico',
      'Cochrane',
      'Coyhaique',
      'Puerto Aysén',
    ],
  },
  'magallanes': {
    comunas: [
      'Antártica',
      'Cabo de Hornos',
      'Laguna Blanca',
      'Natales',
      'Porvenir',
      'Primavera',
      'Punta Arenas',
      'Río Verde',
      'San Gregorio',
      'Timaukel',
      'Torres del Paine',
    ],
    ciudades: [
      'Porvenir',
      'Puerto Natales',
      'Puerto Williams',
      'Punta Arenas',
    ],
  },
  'metropolitana': {
    comunas: [
      'Alhué',
      'Buin',
      'Calera de Tango',
      'Cerrillos',
      'Cerro Navia',
      'Colina',
      'Conchalí',
      'Curacaví',
      'El Bosque',
      'El Monte',
      'Estación Central',
      'Huechuraba',
      'Independencia',
      'Isla de Maipo',
      'La Cisterna',
      'La Florida',
      'La Granja',
      'La Pintana',
      'La Reina',
      'Lampa',
      'Las Condes',
      'Lo Barnechea',
      'Lo Espejo',
      'Lo Prado',
      'Macul',
      'Maipú',
      'María Pinto',
      'Melipilla',
      'Ñuñoa',
      'Padre Hurtado',
      'Paine',
      'Pedro Aguirre Cerda',
      'Peñaflor',
      'Peñalolén',
      'Pirque',
      'Providencia',
      'Pudahuel',
      'Puente Alto',
      'Quilicura',
      'Quinta Normal',
      'Recoleta',
      'Renca',
      'San Bernardo',
      'San Joaquín',
      'San José de Maipo',
      'San Miguel',
      'San Pedro',
      'San Ramón',
      'Santiago',
      'Talagante',
      'Tiltil',
      'Vitacura',
    ],
    ciudades: [
      'Alto Jahuel',
      'Bajos de San Agustín',
      'Batuco',
      'Buin',
      'Chicauma',
      'Ciudad del Valle',
      'Colina',
      'Curacaví',
      'El Monte',
      'Hospital',
      'Isla de Maipo',
      'La Islita',
      'Lampa',
      'Melipilla',
      'Paine',
      'Peñaflor',
      'San José de Maipo',
      'Santiago',
      'Talagante',
      'Tiltil',
    ],
  },
};

/**
 * Comunas de la provincia de Santiago: todas son la misma ciudad (Santiago), y
 * ninguna aparece como ciudad propia en el listado del INE.
 */
const GRAN_SANTIAGO = new Set([
  'Cerrillos',
  'Cerro Navia',
  'Conchalí',
  'El Bosque',
  'Estación Central',
  'Huechuraba',
  'Independencia',
  'La Cisterna',
  'La Florida',
  'La Granja',
  'La Pintana',
  'La Reina',
  'Las Condes',
  'Lo Barnechea',
  'Lo Espejo',
  'Lo Prado',
  'Macul',
  'Maipú',
  'Ñuñoa',
  'Padre Hurtado',
  'Pedro Aguirre Cerda',
  'Peñalolén',
  'Providencia',
  'Pudahuel',
  'Puente Alto',
  'Quilicura',
  'Quinta Normal',
  'Recoleta',
  'Renca',
  'San Bernardo',
  'San Joaquín',
  'San Miguel',
  'San Ramón',
  'Santiago',
  'Vitacura',
]);

const sinTildes = (s: string) =>
  s.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase().trim();

function todas(campo: 'comunas' | 'ciudades'): string[] {
  const set = new Set<string>();
  for (const r of Object.values(CHILE_GEO)) for (const v of r[campo]) set.add(v);
  return [...set].sort((a, b) => a.localeCompare(b, 'es'));
}

/** Comunas de una región; sin región, las de todo el país. */
export function comunasDe(regionId?: string | null): string[] {
  return (regionId && CHILE_GEO[regionId]?.comunas) || todas('comunas');
}

/** Ciudades de una región; sin región, las de todo el país. */
export function ciudadesDe(regionId?: string | null): string[] {
  return (regionId && CHILE_GEO[regionId]?.ciudades) || todas('ciudades');
}

/**
 * Devuelve el nombre canónico si el valor calza con alguno de la lista
 * ignorando mayúsculas y tildes ('SANTIAGO' → 'Santiago'), o null si no calza.
 */
export function canonizar(valor: string | null | undefined, opciones: string[]): string | null {
  if (!valor) return null;
  const objetivo = sinTildes(valor);
  return opciones.find((o) => sinTildes(o) === objetivo) ?? null;
}

/** Nombre canónico de una comuna en todo el país (o null si no existe). */
export function canonizarComuna(valor: string | null | undefined): string | null {
  return canonizar(valor, todas('comunas'));
}

/** Nombre canónico de una ciudad en todo el país (o null si no existe). */
export function canonizarCiudad(valor: string | null | undefined): string | null {
  return canonizar(valor, todas('ciudades'));
}

/** Región a la que pertenece una comuna — para completar fichas antiguas. */
export function regionDeComuna(valor: string | null | undefined): string | null {
  if (!valor) return null;
  const objetivo = sinTildes(valor);
  for (const [rid, geo] of Object.entries(CHILE_GEO)) {
    if (geo.comunas.some((c) => sinTildes(c) === objetivo)) return rid;
  }
  return null;
}

/**
 * Ciudad que corresponde a una comuna, cuando es evidente: la comuna es también
 * ciudad (Valdivia, Ovalle…) o pertenece al Gran Santiago. Si no, null y la
 * elige el usuario.
 */
export function ciudadDeComuna(comuna: string | null | undefined): string | null {
  if (!comuna) return null;
  if (GRAN_SANTIAGO.has(comuna)) return 'Santiago';
  return canonizarCiudad(comuna);
}

/** Nombre de la región para mostrar (usa el catálogo del simulador). */
export function nombreRegion(regionId: string | null | undefined): string | null {
  if (!regionId) return null;
  return REGIONS.find((r) => r.id === regionId)?.name ?? null;
}
